### ISSUE TITLE
Panic while parsing

### ISSUE THREAD

**Issue by bboreham** [fatih/faillint#40]
Seen at https://github.com/grafana/mimir/actions/runs/8520707102/job/23337387670?pr=7356

Of interest, this is a PR to bump Go version from 1.21 to 1.22.  

Since this repo seems moribund, we will try https://github.com/OpenPeeDeeP/depguard.

```
GOFLAGS="-tags=requires_docker,stringlabels" faillint -paths "github.com/bmizerany/assert=github.com/stretchr/testify/assert,\
	golang.org/x/net/context=context,\
	sync/atomic=go.uber.org/atomic,\
	regexp=github.com/grafana/regexp,\
	github.com/go-kit/kit/log/...=github.com/go-kit/log,\
	github.com/prometheus/client_golang/prometheus.{MultiError}=github.com/prometheus/prometheus/tsdb/errors.{NewMulti},\
	github.com/weaveworks/common/user.{ExtractOrgID}=github.com/grafana/mimir/pkg/tenant.{TenantID,TenantIDs},\
	github.com/weaveworks/common/user.{ExtractOrgIDFromHTTPRequest}=github.com/grafana/mimir/pkg/tenant.{ExtractTenantIDFromHTTPRequest}" ./pkg/... ./cmd/... ./tools/... ./integration/...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b25ef]

goroutine 95 [running]:
go/types.(*Checker).handleBailout(0xc0001b0400, 0xc004179c60)
	/usr/local/go/src/go/types/check.go:367 +0x88
panic({0x7192e0?, 0x9a4b20?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x7e7e90, 0x9a87e0})
	/usr/local/go/src/go/types/sizes.go:228 +0x30f
go/types.(*Config).sizeof(...)
	/usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x7e7e90?, 0x9a87e0?})
	/usr/local/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0x7e91f0, 0x99d4a0}, 0xc0001b0400, 0x9a87e0, 0xc004178078)
	/usr/local/go/src/go/types/const.go:92 +0x192
[...]
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x6d696d2f72696d69?, 0x6f646e65762f7269?)
	/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:826 +0x4a
golang.org/x/tools/go/packages.(*loader).refine.func2(0x2f33762f676b702f?)
	/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:761 +0x26
created by golang.org/x/tools/go/packages.(*loader).refine in goroutine 1
	/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:760 +0xc9a
make: *** [Makefile:308: lint] Error 2
```

**Comment by pstibrany** [comment]
This is now fixed in https://github.com/fatih/faillint/releases/tag/v1.12.0
